version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - "4000:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.24.0
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command:
      - --searchPath=/liquibase/changelog
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/postgresql
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    networks:
      - app-network
    restart: "no"

  bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data: